// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    audit_registry
    (
        init => init
        register_audit => register_audit
        get_all_audits => get_all_audits
        getTotalContracts => get_total_contracts
        getContractAudits => get_contract_audits
        getAuditorHistory => get_auditor_history
        getLatestAudit => get_latest_audit
        withdraw => withdraw
        getOwner => owner
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
